DROP DATABASE IF EXISTS burger_db;

CREATE DATABASE burger_db;
USE burgershop_db;

CREATE TABLE burger_db(
id INT NOT NULL AUTO_INCREMENT, 
burger_name VARCHAR(500) NOT NULL,
devoured BOOLEAN NOT NULL DEFAULT 0, 
createdAt TIMESTAMP NOT NULL,
PRIMARY KEY (id)
);